# Generated by Django 2.0.5 on 2018-12-07 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('avgstars', models.CharField(max_length=3)),
                ('categories', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('birthdate', models.DateField()),
                ('location', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('stars', models.CharField(max_length=3)),
                ('prediction', models.CharField(max_length=3)),
                ('rid', models.CharField(default='', editable=False, max_length=30)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Business')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='reviews',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Users'),
        ),
    ]
