# Generated by Django 2.0.5 on 2018-12-07 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='prediction',
            field=models.IntegerField(max_length=3),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='rid',
            field=models.CharField(max_length=30),
        ),
    ]
