# Generated by Django 2.0.5 on 2018-12-07 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20181207_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='prediction',
            field=models.CharField(max_length=3),
        ),
    ]
